task: ctr

dataset:
  name: criteo_csv
  path: data/criteo_small.csv           # 需你自行放置 (label, I1..I13, C1..C26)
  label_col: label
  dense_cols: [I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13]
  cat_cols: [C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16, C17, C18, C19, C20, C21, C22, C23, C24, C25, C26]
  freq_threshold: 5
  hash_bins: 2000000

split:
  method: random
  train_ratio: 0.9
  seed: 42

model:
  name: fm
  params:
    factors: 16
    lr: 0.05
    reg_w: 1e-6
    reg_v: 1e-6
    epochs: 3
    batch_size: 65536
    seed: 42

metrics: ["AUC", "LogLoss"]

trainer:
  name: ctr_offline
